repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/thoughtworks/talisman
  rev: 'v1.28.0'
  hooks:
  - id: talisman-commit
    entry: cmd --githook pre-commit
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v9.9.0
  hooks:
  - id: eslint
